#!/bin/bash

# Script to set up the directory structure for Libertom Financial Platform

# Create uploads directory structure
mkdir -p public/uploads/kyc/id_documents
mkdir -p public/uploads/kyc/proof_of_address
mkdir -p public/uploads/kyc/selfies
mkdir -p public/uploads/kyc/additional
mkdir -p public/uploads/profile/avatars
mkdir -p public/uploads/temp

# Create build directory (normally generated by Vite)
mkdir -p public/build/assets/images/icons

# Create css directory
mkdir -p public/css

# Create js directory
mkdir -p public/js

echo "Directory structure created successfully!"
